PrefixoBroadcast: "[SeuServidor]"
PrefixoRaw: ""

PermissaoStreamer: "hbroadcast.streamer"
PermissaoAdministrador: "hbroadcast.adm"
PermissaoVIP: "hbroadcast.vip"


ComandoIncompleto: "O comando que você digitou está incompleto."
ComandoSemPermissao: "Você não possui permissão para executar esse comando."


PrefixoSubComandoAnunciarNormal: "hnormal"
PrefixoSubComandoAnunciarRaw: "hraw"
PrefixoSubComandoAnunciarLive: "hlive"