name: hBroadcast
main: team.martin.hbroadcast.hBroadcast
version: 1.4
api-version: 1.16
authors: [ Martinfer22 ]
website: huddouting.team
commands:
  anunciar:
    description: Anuncie com a predefinição que você escolheu na config.yml